//
//  skills.swift
//  JobApp
//
//  Created by thanks on 7/30/17.
//  Copyright © 2017 Admin. All rights reserved.
//

import Foundation

public class Skills{
    
    public static let skills : [String] = ["java script",
                                          "Business Planning & Analysis",
                                          ".Net",
                                          ".Net ASP.NET C# SQL",
                                          ".Net MVC ASP.NET LINQ",
                                          ".Net MVC WCF",
                                          ".Net WPF",
                                          "2G",
                                          "3d character animation",
                                          "3D Max",
                                          "3d printing",
                                          "3dmax",
                                          "3DVIA",
                                          "3G",
                                          "4G",
                                          "A+",
                                          "ACCESS",
                                          "Accessories",
                                          "account finalisaton",
                                          "Account Management",
                                          "Accounting",
                                          "Accounting and Finance",
                                          "Accounts & Finance",
                                          "ActiveX",
                                          "ad booking",
                                          "Administration",
                                          "Adobe CQ",
                                          "Adobe After Effects",
                                          "Adobe Flash",
                                          "Adobe Dreamweaver",
                                          "Adobe Form",
                                          "Adobe Illustrator",
                                          "adobe indesign",
                                          "adobe Livecycle",
                                          "Adobe Pagemaker",
                                          "Adobe Photoshop",
                                          "adobe photoshop lightroom",
                                          "adobe premiere",
                                          "adobe PREMIERE PRO",
                                          "Advance excel",
                                          "Advance Sas",
                                          "advance sql",
                                          "Advanced analytics",
                                          "Advanced C Programming",
                                          "Advanced SQL",
                                          "Agile",
                                          "AJAX",
                                          "ALP",
                                          "Amazon Aws",
                                          "Analysis",
                                          "Android",
                                          "android audio",
                                          "Android Native",
                                          "android ndk",
                                          "Angular",
                                          "AngularJS",
                                          "Animation",
                                          "Apache",
                                          "API",
                                          "Apple",
                                          "Application",
                                          "AR",
                                          "ARM",
                                          "ARMv7",
                                          "ASP.NET",
                                          "ASP",
                                          "AutoCAD",
                                          "AWS",
                                          "Backend",
                                          "backbone.js",
                                          "Banking",
                                          "BASIC",
                                          "basic c++",
                                          "Billing",
                                          "bioinformatics",
                                          "Blackberry",
                                          "Bluetooth",
                                          "Bloomberg",
                                          "Boost",
                                          "Business",
                                          "C#",
                                          "C++",
                                          "C/C++",
                                          "Cash",
                                          "cctv",
                                          "Channels",
                                          "cloud",
                                          "Cloth",
                                          "Clipper",
                                          "codec",
                                          "Composing",
                                          "Components",
                                          "Content",
                                          "Cooking",
                                          "cosmos",
                                          "Customer",
                                          "cvs",
                                          "Data Analytics",
                                          "Data Architecture",
                                          "Data Modeling",
                                          "Database",
                                          "DB2",
                                          "Debugging",
                                          "Delphi",
                                          "dell",
                                          "Design",
                                          "Digital",
                                          "Document",
                                          "Dynamics",
                                          "e-commerce",
                                          "ec2",
                                          "Electrical",
                                          "Email",
                                          "Embedded",
                                          "Embedded C",
                                          "Embedded c++",
                                          "Embedded Software",
                                          "energy",
                                          "Engineering",
                                          "Enterprise",
                                          "enterprise architecture",
                                          "Enterprise Accounts",
                                          "Enterprise VOIP",
                                          "Environment",
                                          "ERP",
                                          "esp",
                                          "Event",
                                          "Event Management",
                                          "fashion",
                                          "FileNet",
                                          "Film Editing",
                                          "Finacle",
                                          "Finance",
                                          "Finance Analyst",
                                          "Firewall",
                                          "Foreign Exchange",
                                          "Fund transfer",
                                          "Game",
                                          "G&A",
                                          "gas turbine",
                                          "Gateway",
                                          "gcc",
                                          "Github",
                                          "git",
                                          "glovia",
                                          "google api",
                                          "google adwords",
                                          "google analytics",
                                          "google map",
                                          "grid",
                                          "haml",
                                          "health care",
                                          "heap dump",
                                          "healthcare",
                                          "HLS",
                                          "html/css",
                                          "html5",
                                          "html4",
                                          "HTTPS",
                                          "Hybrid",
                                          "IBM",
                                          "Ideas",
                                          "IHS",
                                          "IFS",
                                          "Image Processing",
                                          "IMS",
                                          "Industrial Buildings",
                                          "Industry Analysis",
                                          "informaitca",
                                          "Interact",
                                          "investment analysis",
                                          "invoicing",
                                          "iOS",
                                          "iOS Application",
                                          "ip camera",
                                          "Ip Security",
                                          "IP technology",
                                          "iso",
                                          "IT",
                                          "Java",
                                          "JSP",
                                          "Objective C",
                                          "Swift2",
                                          "Swift3",
                                          "MFC",
                                          "Photoshop"
                                          ]
}
